Update patch set 7
Patch Set 7:

Am I missing something?

    hardware/qcom/power/power-8953.c:308:5: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    clock_gettime(CLOCK_MONOTONIC, &cur_boost_timespec);
    ^
    hardware/qcom/power/power-8953.c:308:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(CLOCK_MONOTONIC, &cur_boost_timespec);
                  ^

Patch-set: 7
Reviewer: Gerrit User 4550 <4550@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>